In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np

In [3]:
a0 = np.array(9)

In [4]:
print(a0)

9


In [5]:
a1=np.array([1, 3, 5, 7, 9])

In [6]:
print(a1)

[1 3 5 7 9]


In [9]:
a2=np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])

In [10]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
a3 = np.array([[[1, 2], 
                [3, 4]], 
               [[5, 6], 
               [7, 8]], 
              [[9, 10], 
               [11, 12]]])
print(a3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [16]:
AR = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(AR)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [17]:
AR.shape

(12,)

In [18]:
AR2 = AR.reshape(3, 4)

In [19]:
print(AR2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
AR2.shape

(3, 4)

In [22]:
AR3 = AR.reshape(3, 2, 2)

In [23]:
print(AR3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [24]:
AR3.shape

(3, 2, 2)

In [25]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(1, 10). reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.random.rand(3, 2, 2)

array([[[0.72755756, 0.49942426],
        [0.05275641, 0.08172821]],

       [[0.17107548, 0.86694635],
        [0.66027466, 0.30588281]],

       [[0.39025259, 0.06341352],
        [0.08905015, 0.08797753]]])

In [34]:
np.random.randint(1, 45, size = (5, 6))

array([[37, 13,  7, 43, 35, 27],
       [28, 33, 34,  2,  7,  6],
       [18,  4, 35, 38, 41, 29],
       [19, 16,  6, 27, 21, 14],
       [31, 29, 36,  8,  1, 27]])

In [35]:
np.random.seed(2045)

In [39]:
np.random.choice(np.arange(1, 46), size = (5, 6), replace = False)
#replace = False 는 중복 허용 X

array([[12, 15, 40,  6, 36, 37],
       [44, 11, 19, 22,  8, 31],
       [42, 39, 43, 33,  2,  1],
       [30,  5, 26,  7,  9, 17],
       [14,  3, 16, 38, 24, 35]])

In [40]:
a1 = np.array([1, 3, 5, 7, 9])
a2 = np.array([10, 30, 50, 70, 90])

In [41]:
a1 + a2

array([11, 33, 55, 77, 99])

In [42]:
a2 - a1

array([ 9, 27, 45, 63, 81])

In [43]:
a1 * a2

array([ 10,  90, 250, 490, 810])

In [44]:
a2/a1

array([10., 10., 10., 10., 10.])

In [45]:
a1 * 3

array([ 3,  9, 15, 21, 27])

In [46]:
a1 ** 2

array([ 1,  9, 25, 49, 81])

In [47]:
a1.sum()

25

In [48]:
a2.mean()

50.0

In [49]:
a2.var()

800.0

In [50]:
a2.std()

28.284271247461902

In [51]:
a2.min()

10

In [52]:
a2.max()

90

In [53]:
a1.cumsum()

array([ 1,  4,  9, 16, 25])

In [54]:
a1.cumprod()

array([  1,   3,  15, 105, 945])

In [55]:
A1 = np.array([2, 4, 6, 8]).reshape(2,2)

In [56]:
print(A1)

[[2 4]
 [6 8]]


In [57]:
A2= np.array([3, 5, 7, 8]).reshape(2, 2)

In [58]:
print(A2)

[[3 5]
 [7 8]]


In [59]:
A1.dot(A2)

array([[34, 42],
       [74, 94]])

In [60]:
np.dot(A2, A1)

array([[36, 52],
       [62, 92]])

In [61]:
A1 * A2

array([[ 6, 20],
       [42, 64]])

In [62]:
np.transpose(A1)

array([[2, 6],
       [4, 8]])

In [63]:
A2.transpose()

array([[3, 7],
       [5, 8]])

In [64]:
!ls -l

total 20
-rw-r--r-- 1 root root   723 Feb 22 08:31 PII.csv
-rw-r--r-- 1 root root 11370 Feb 22 08:31 PII.xlsx
drwxr-xr-x 1 root root  4096 Feb 16 16:35 sample_data


In [65]:
import pandas as pd

In [67]:
DF1 = pd.read_csv('PII.csv')

In [68]:
DF1

Name Gender  Age  Grade Picture BloodType  Height  Weight
0   송태섭     남자   21      3       무         B   179.1    63.9
1   최유정     여자   23      1       유         A   177.1    54.9
2   이한나     여자   20      1       무         A   167.9    50.2
3   김소혜     여자   23      3       무         O   176.1    53.5
4   서태웅     남자   24      4       무         B   176.1    79.8
5   정대만     남자   24      2       유         B   175.2    61.7
6   이정환     남자   22      4       무         B   169.1    69.8
7   채소연     여자   22      2       유        AB   169.9    52.7
8   강백호     남자   23      3       무         O   165.5    68.5
9   전소미     여자   22      2       유         O   161.9    52.3
10  변덕규     남자   21      1       무         A   163.2    55.5
11  정채연     여자   22      2       무         B   157.8    44.9
12  권준호     남자   24      4       유         O   166.9    61.7
13  채치수     남자   23      3       무        AB   181.8    85.9
14  윤대협     남자   22      2       유        AB   180.3    76.2
15  김세정     여자   21      1       무         O   155.5    44.9
16  신준섭     남자   23      1       무         A   168.9    62.7

In [69]:
DF2 = pd.read_excel('PII.xlsx')

In [70]:
DF2

Name Gender  Age  Grade Picture BloodType  Height  Weight
0   송태섭     남자   21      3       무         B   179.1    63.9
1   최유정     여자   23      1       유         A   177.1    54.9
2   이한나     여자   20      1       무         A   167.9    50.2
3   김소혜     여자   23      3       무         O   176.1    53.5
4   서태웅     남자   24      4       무         B   176.1    79.8
5   정대만     남자   24      2       유         B   175.2    61.7
6   이정환     남자   22      4       무         B   169.1    69.8
7   채소연     여자   22      2       유        AB   169.9    52.7
8   강백호     남자   23      3       무         O   165.5    68.5
9   전소미     여자   22      2       유         O   161.9    52.3
10  변덕규     남자   21      1       무         A   163.2    55.5
11  정채연     여자   22      2       무         B   157.8    44.9
12  권준호     남자   24      4       유         O   166.9    61.7
13  채치수     남자   23      3       무        AB   181.8    85.9
14  윤대협     남자   22      2       유        AB   180.3    76.2
15  김세정     여자   21      1       무         O   155.5    44.9
16  신준섭     남자   23      1       무         A   168.9    62.7

In [71]:
type(DF1)

pandas.core.frame.DataFrame

In [72]:
DF1.index

RangeIndex(start=0, stop=17, step=1)

In [73]:
DF1.columns

Index(['Name', 'Gender', 'Age', 'Grade', 'Picture', 'BloodType', 'Height',
       'Weight'],
      dtype='object')

In [74]:
DF1.values

array([['송태섭', '남자', 21, 3, '무', 'B', 179.1, 63.9],
       ['최유정', '여자', 23, 1, '유', 'A', 177.1, 54.9],
       ['이한나', '여자', 20, 1, '무', 'A', 167.9, 50.2],
       ['김소혜', '여자', 23, 3, '무', 'O', 176.1, 53.5],
       ['서태웅', '남자', 24, 4, '무', 'B', 176.1, 79.8],
       ['정대만', '남자', 24, 2, '유', 'B', 175.2, 61.7],
       ['이정환', '남자', 22, 4, '무', 'B', 169.1, 69.8],
       ['채소연', '여자', 22, 2, '유', 'AB', 169.9, 52.7],
       ['강백호', '남자', 23, 3, '무', 'O', 165.5, 68.5],
       ['전소미', '여자', 22, 2, '유', 'O', 161.9, 52.3],
       ['변덕규', '남자', 21, 1, '무', 'A', 163.2, 55.5],
       ['정채연', '여자', 22, 2, '무', 'B', 157.8, 44.9],
       ['권준호', '남자', 24, 4, '유', 'O', 166.9, 61.7],
       ['채치수', '남자', 23, 3, '무', 'AB', 181.8, 85.9],
       ['윤대협', '남자', 22, 2, '유', 'AB', 180.3, 76.2],
       ['김세정', '여자', 21, 1, '무', 'O', 155.5, 44.9],
       ['신준섭', '남자', 23, 1, '무', 'A', 168.9, 62.7]], dtype=object)

In [75]:
DF1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Name       17 non-null     object 
 1   Gender     17 non-null     object 
 2   Age        17 non-null     int64  
 3   Grade      17 non-null     int64  
 4   Picture    17 non-null     object 
 5   BloodType  17 non-null     object 
 6   Height     17 non-null     float64
 7   Weight     17 non-null     float64
dtypes: float64(2), int64(2), object(4)
memory usage: 1.2+ KB


In [76]:
DF1.head()

Name Gender  Age  Grade Picture BloodType  Height  Weight
0  송태섭     남자   21      3       무         B   179.1    63.9
1  최유정     여자   23      1       유         A   177.1    54.9
2  이한나     여자   20      1       무         A   167.9    50.2
3  김소혜     여자   23      3       무         O   176.1    53.5
4  서태웅     남자   24      4       무         B   176.1    79.8

In [77]:
DF1[0:5]

Name Gender  Age  Grade Picture BloodType  Height  Weight
0  송태섭     남자   21      3       무         B   179.1    63.9
1  최유정     여자   23      1       유         A   177.1    54.9
2  이한나     여자   20      1       무         A   167.9    50.2
3  김소혜     여자   23      3       무         O   176.1    53.5
4  서태웅     남자   24      4       무         B   176.1    79.8

In [79]:
DF1.tail(3)

Name Gender  Age  Grade Picture BloodType  Height  Weight
14  윤대협     남자   22      2       유        AB   180.3    76.2
15  김세정     여자   21      1       무         O   155.5    44.9
16  신준섭     남자   23      1       무         A   168.9    62.7

In [80]:
DF1[-3:]

Name Gender  Age  Grade Picture BloodType  Height  Weight
14  윤대협     남자   22      2       유        AB   180.3    76.2
15  김세정     여자   21      1       무         O   155.5    44.9
16  신준섭     남자   23      1       무         A   168.9    62.7

In [81]:
DF1.describe()

Age      Grade      Height     Weight
count  17.000000  17.000000   17.000000  17.000000
mean   22.352941   2.294118  170.135294  61.123529
std     1.169464   1.104802    7.853896  11.867894
min    20.000000   1.000000  155.500000  44.900000
25%    22.000000   1.000000  165.500000  52.700000
50%    22.000000   2.000000  169.100000  61.700000
75%    23.000000   3.000000  176.100000  68.500000
max    24.000000   4.000000  181.800000  85.900000

In [82]:
DF1.mean()

Age        22.352941
Grade       2.294118
Height    170.135294
Weight     61.123529
dtype: float64

In [83]:
type(DF1['Height'])

pandas.core.series.Series

In [86]:
DF1[['Height', 'Age']]

Height  Age
0    179.1   21
1    177.1   23
2    167.9   20
3    176.1   23
4    176.1   24
5    175.2   24
6    169.1   22
7    169.9   22
8    165.5   23
9    161.9   22
10   163.2   21
11   157.8   22
12   166.9   24
13   181.8   23
14   180.3   22
15   155.5   21
16   168.9   23

In [88]:
DF1.Height

0     179.1
1     177.1
2     167.9
3     176.1
4     176.1
5     175.2
6     169.1
7     169.9
8     165.5
9     161.9
10    163.2
11    157.8
12    166.9
13    181.8
14    180.3
15    155.5
16    168.9
Name: Height, dtype: float64

In [89]:
DF1['Height'].sum()

2892.2999999999997

In [90]:
DF1['Height'].mean()

170.1352941176471

In [91]:
DF1['Height'].var()

61.683676470588225

In [92]:
DF1['Height'].std()

7.8538956238664275

In [93]:
DF1['Height'].min()

155.5

In [94]:
DF1['Height'].max()

181.8

In [95]:
DF1.groupby(['BloodType']).mean()

Age     Grade      Height  Weight
BloodType                                         
A          21.750000  1.000000  169.275000  55.825
AB         22.333333  2.333333  177.333333  71.600
B          22.600000  3.000000  171.460000  64.020
O          22.600000  2.600000  165.180000  56.180

In [97]:
DF1.groupby(['BloodType'])['Height'].mean()

BloodType
A     169.275000
AB    177.333333
B     171.460000
O     165.180000
Name: Height, dtype: float64

In [98]:
DF1.Height[16]

168.9

In [99]:
DF1.Height[0:5]

0    179.1
1    177.1
2    167.9
3    176.1
4    176.1
Name: Height, dtype: float64